CREATE TABLE CUSTOMER(
	CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CUSTOMER_FNAME VARCHAR(30) NOT NULL,
	CUSTOMER_LNAME VARCHAR(30) NOT NULL
);

CREATE TABLE ORDER(
	ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ORDER_CUSTOMER_ID BIGINT NOT NULL,
	DATE_ORDERED DATE NOT NULL,
	DATE_SHIPPED DATE,
	FOREIGN KEY (ORDER_CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);